numero=int(input('Digite um número: '))
print('-'*9)
print('{}x1={}'.format(numero,numero*1))
print('{}x2={}'.format(numero,numero*2))
print('{}x3={}'.format(numero,numero*3))
print('{}x4={}'.format(numero,numero*4))
print('{}x5={}'.format(numero,numero*5))
print('{}x6={}'.format(numero,numero*6))
print('{}x7={}'.format(numero,numero*7))
print('{}x8={}'.format(numero,numero*8))
print('{}x9={}'.format(numero,numero*9))
print('{}x10={}'.format(numero,numero*10))
print('-'*9)
