n=input('Digite algo: ')
print('n é ',type(n))
print('n só tem espeços? ',n.isspace())
print('n é um número? ',n.isnumeric())
print('n é decimal? ',n.isdecimal())
print('n é alfabético? ',n.isalpha())
print('n é alfa numérico? ',n.isalnum())
print('n é um digito? ',n.isdigit())
print('n está em minúsculo? ',n.islower())
print('n está em maiúculo? ',n.isupper())
print('n está capitalizado? ',n.istitle())
